export default {
    backgroundColor: '#1D1D1D',
    calendarBackground: '#4b4b4b',
    textSectionTitleColor: '#ffffffd1',
    selectedDayBackgroundColor: '#B84DC1',
    selectedDayTextColor: '#ffffff',
    todayTextColor: '#e800bf',
    dayTextColor: '#ffffff',
    textDisabledColor: '#d9e1e8',
    dotColor: '#B84DC1',
    selectedDotColor: '#B84DC1',
    arrowColor: 'orange',
    disabledArrowColor: '#d9e1e8',
    monthTextColor: '#ffffff',
    indicatorColor: '#B84DC1',
    textDayFontFamily: 'Nunito_600SemiBold',
    textMonthFontFamily: 'Nunito_800ExtraBold',
    textDayHeaderFontFamily: 'Nunito_700Bold',
    textDayFontWeight: '600',
    textMonthFontWeight: '800',
    textDayHeaderFontWeight: '700',
    textDayFontSize: 14,
    textMonthFontSize: 18,
    textDayHeaderFontSize: 14,
    agendaDayNumColor: "#95419c",
    agendaTodayColor: "#95419c",
    agendaDayTextColor: "#95419c"
}